name: Publish Release

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module to publish'
        required: false
        type: choice
        default: all
        options:
          - all
          - maestro-utils
          - maestro-client
          - maestro-ios
          - maestro-orchestra
          - maestro-orchestra-models
          - maestro-proto
          - maestro-ios-driver
          - maestro-ai
          - maestro-web
          - maestro-cli
  push:
    tags:
      - 'v*'

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ vars.MAVEN_CENTRAL_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}
  PUBLISH_MODULE: ${{ github.event_name == 'workflow_dispatch' && inputs.module || 'all' }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'Entertech/Maestro'

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Retrieve version
        run: |
          echo "VERSION_NAME=$(cat gradle.properties | grep -w "VERSION_NAME" | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Upload Maestro utils release
        run: ./gradlew clean :maestro-utils:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-utils') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro client release
        run: ./gradlew clean :maestro-client:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-client') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro ios release
        run: ./gradlew clean :maestro-ios:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-ios') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro orchestra release
        run: ./gradlew clean :maestro-orchestra:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-orchestra') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro Orchestra Models release
        run: ./gradlew clean :maestro-orchestra-models:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-orchestra-models') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro Proto release
        run: ./gradlew clean :maestro-proto:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-proto') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro XCUiTest Driver
        run: ./gradlew clean :maestro-ios-driver:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-ios-driver') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro AI release
        run: ./gradlew clean :maestro-ai:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-ai') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro Web release
        run: ./gradlew clean :maestro-web:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-web') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}

      - name: Upload Maestro CLI release
        run: ./gradlew clean :maestro-cli:publishToMavenCentral --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') && (env.PUBLISH_MODULE == 'all' || env.PUBLISH_MODULE == 'maestro-cli') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.ORG_GRADLE_PROJECT_mavenCentralPassword }}
